import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'log_types.dart';

class ProGuardService {
  Future<String> _ensureJar() async {
    final dir = await getTemporaryDirectory();
    final target = p.join(dir.path, 'proguard.jar');
    final targetFile = File(target);

    final bundleData = await _readBundledJar();
    await targetFile.writeAsBytes(bundleData, flush: true);
    return target;
  }

  Future<List<int>> _readBundledJar() async {
    final candidates = [
      p.join(Directory.current.path, 'assets', 'tools', 'proguard.jar'),
      p.join(p.dirname(Platform.resolvedExecutable), 'data', 'flutter_assets', 'assets', 'tools', 'proguard.jar'),
      p.join(p.dirname(Platform.resolvedExecutable), 'assets', 'tools', 'proguard.jar'),
    ];
    for (final path in candidates) {
      final f = File(path);
      if (await f.exists()) {
        return await f.readAsBytes();
      }
    }
    throw StateError('proguard.jar not found in any expected location');
  }

  Future<bool> run({
    required String inputJar,
    required String outputJar,
    required String mainClass,
    required String javaPath,
    required String jdkPath,
    required bool keepResources,
    required LogSink log,
    String? javafxSdkPath,
  }) async {
    final proguardJar = await _ensureJar();
    final dir = await getTemporaryDirectory();
    final workDir = p.join(
      dir.path,
      'jpackage_gui_pg_${DateTime.now().millisecondsSinceEpoch}',
    );
    await Directory(workDir).create(recursive: true);

    final configPath = p.join(workDir, 'proguard.pro');
    final config = _generateConfig(
      inputJar: inputJar,
      outputJar: outputJar,
      mainClass: mainClass,
      jdkPath: jdkPath,
      keepResources: keepResources,
      javafxSdkPath: javafxSdkPath,
    );
    await File(configPath).writeAsString(config);

    final args = ['-jar', proguardJar, '@$configPath'];

    log('[ProGuard] java ${args.join(' ')}', LogLevel.command);
    final ok = await _runProcess(javaPath, args, log: log, tag: '[ProGuard]');
    if (!ok) {
      log('[ProGuard] 混淆失败', LogLevel.error);
      return false;
    }
    log('[ProGuard] 混淆完成: $outputJar', LogLevel.success);
    return true;
  }

  String _generateConfig({
    required String inputJar,
    required String outputJar,
    required String mainClass,
    required String jdkPath,
    required bool keepResources,
    String? javafxSdkPath,
  }) {
    final sb = StringBuffer();
    sb.writeln('# Auto-generated by JPackage GUI');
    sb.writeln('-dontshrink');
    sb.writeln('-dontoptimize');
    sb.writeln('-dontwarn');
    sb.writeln('-ignorewarnings');
    sb.writeln('-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,SourceFile,LineNumberTable');
    sb.writeln();
    sb.writeln('# JDK 模块作为 libraryjars，提供 java.lang.* 等基类');
    const jmods = [
      'java.base',
      'java.desktop',
      'java.xml',
      'java.prefs',
      'java.logging',
      'java.management',
      'java.naming',
      'java.net.http',
      'java.sql',
      'java.transaction.xa',
      'java.scripting',
      'java.compiler',
      'java.instrument',
      'java.datatransfer',
      'java.rmi',
      'java.security.jgss',
      'java.smartcardio',
    ];
    final jmodsDir = p.join(jdkPath, 'jmods');
    for (final mod in jmods) {
      sb.writeln('-libraryjars "${p.join(jmodsDir, '$mod.jmod')}"');
    }
    // JavaFX 作为 library：否则 start(Stage) 等方法名会被当成普通方法重命名
    if (javafxSdkPath != null && javafxSdkPath.isNotEmpty) {
      final fxLib = p.join(javafxSdkPath, 'lib');
      for (final name in const [
        'javafx.base.jar',
        'javafx.graphics.jar',
        'javafx.controls.jar',
        'javafx.fxml.jar',
        'javafx.media.jar',
        'javafx.swing.jar',
        'javafx.web.jar',
      ]) {
        final jarPath = p.join(fxLib, name);
        if (File(jarPath).existsSync()) {
          sb.writeln('-libraryjars "$jarPath"');
        }
      }
    }
    sb.writeln();
    sb.writeln('-injars "$inputJar"');
    sb.writeln('-outjars "$outputJar"');
    sb.writeln();
    sb.writeln('# 保留入口类（含 main）');
    sb.writeln('-keep public class $mainClass {');
    sb.writeln('    public static void main(java.lang.String[]);');
    sb.writeln('    public <init>();');
    sb.writeln('}');
    sb.writeln();
    sb.writeln('# 保留所有 JavaFX Application 子类的生命周期方法名（禁止 start->a）');
    sb.writeln('-keep public class * extends javafx.application.Application {');
    sb.writeln('    public <init>();');
    sb.writeln('    public static void main(java.lang.String[]);');
    sb.writeln('    public void start(javafx.stage.Stage);');
    sb.writeln('    public void init();');
    sb.writeln('    public void stop();');
    sb.writeln('}');
    sb.writeln('-keepclassmembers class * extends javafx.application.Application {');
    sb.writeln('    public void start(javafx.stage.Stage);');
    sb.writeln('    public void init();');
    sb.writeln('    public void stop();');
    sb.writeln('}');
    sb.writeln();
    sb.writeln('# 保留 FXML 注入字段和方法（onAction 等事件处理器）');
    sb.writeln('-keep class * {');
    sb.writeln('    @javafx.fxml.FXML <fields>;');
    sb.writeln('    @javafx.fxml.FXML <methods>;');
    sb.writeln('}');
    sb.writeln();
    sb.writeln('# 保留 Controller 类（FXML fx:controller 引用类名、字段名和方法名）');
    sb.writeln('-keep class **Controller {');
    sb.writeln('    <fields>;');
    sb.writeln('    <methods>;');
    sb.writeln('}');
    sb.writeln();
    sb.writeln('# 保留所有 Initializable 实现类的 initialize 方法');
    sb.writeln('-keepclassmembers class * {');
    sb.writeln('    public void initialize(java.net.URL, java.util.ResourceBundle);');
    sb.writeln('}');
    sb.writeln();
    if (keepResources) {
      // 默认会原样复制资源；切勿使用 -adaptresourcefilecontents，
      // 它会按平台默认编码改写 fxml/properties，破坏 UTF-8 中文导致乱码。
      sb.writeln('-keepdirectories');
      sb.writeln();
    }
    sb.writeln('# 保留枚举的 values/valueOf');
    sb.writeln('-keepclassmembers enum * {');
    sb.writeln('    public static **[] values();');
    sb.writeln('    public static ** valueOf(java.lang.String);');
    sb.writeln('}');
    return sb.toString();
  }

  Future<bool> _runProcess(
    String executable,
    List<String> args, {
    required LogSink log,
    required String tag,
  }) async {
    try {
      final proc = await Process.start(executable, args, runInShell: false);
      final stdoutSub = proc.stdout
          .transform<String>(const SystemEncoding().decoder)
          .transform(const LineSplitter())
          .listen((line) => log('$tag $line', LogLevel.info));
      final stderrSub = proc.stderr
          .transform<String>(const SystemEncoding().decoder)
          .transform(const LineSplitter())
          .listen((line) => log('$tag $line', LogLevel.warning));
      final code = await proc.exitCode;
      await stdoutSub.cancel();
      await stderrSub.cancel();
      return code == 0;
    } catch (e) {
      log('$tag 进程异常: $e', LogLevel.error);
      return false;
    }
  }
}
